name: actions-demo
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout
          uses: actions/checkout@v5
        
        - name: print something
          run: |
            echo "welcome to GIT-HUB ACTIONS"
            ls -lstra
            cat README.md
        - name: Generate ASCII artwork
          run: |
           apt-get install cowsay -y
           cowsay -f dragon "Run for cover, I am a Dragon Rawr..." >>dragon.tx
