name: actions-demo
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: print something
          run: echo "welcome to GIT-HUB ACTIONS"
        
        - name: listing dir
          run: ls -lstra
        
        - name: read-file
          run: cat ../../README.md
