name: ascii generator
on: push
jobs:
    generate-ascii:
        runs-on: ubuntu-latest
        steps:
        - name: actionscheckout
          uses: actions/checkout@v5
        - name: list files
          run: ls -lstra
        - name: run script
          run: |
            chmod +x basic.sh
            ./basic.sh

